-- GENERADO AUTOMATICAMENTE por db/generate-seed.js — NO EDITAR A MANO.
-- Fuente: nutrimetria-inventory.js (32 productos reales NUTRIMETRIA).
-- La ruta fisica NO se guarda: se deriva del SKU en services/assetResolver.js.
-- Las versiones declaradas como NO_CONFIRMADO en los archivos se guardan como PENDIENTE_DE_VALIDACION.

INSERT INTO products (id, sku, name, category, price_clp, version, file_name, active) VALUES
('nmx01', 'NMX-01', 'Calculadora Energética (Necesidades Energéticas)', 'Motor de cálculo energético', 7990, 'PENDIENTE_DE_VALIDACION',
  'NMX-01.xlsx', true),
('nmx09', 'NMX-09', 'Calculadora de Percentiles OMS', 'Motor de percentiles de crecimiento', 6990, 'PENDIENTE_DE_VALIDACION',
  'NMX-09.xlsx', true),
('nmx10', 'NMX-10', 'Motor de Requerimiento Energético, MET y Efecto Térmico', 'Motor de gasto energético', 6990, 'v1.0.1',
  'NMX-10.xlsx', true),
('nmx12', 'NMX-12', 'Calculadora de Grasa y Composición Corporal', 'Motor de composición corporal', 6990, 'PENDIENTE_DE_VALIDACION',
  'NMX-12.xlsx', true),
('nmx16', 'NMX-16', 'Calculadora de Somatotipo y Somatocarta (Heath–Carter)', 'Motor de somatotipo', 6990, 'PENDIENTE_DE_VALIDACION',
  'NMX-16.xlsx', true),
('nmx36', 'NMX-36', 'Calculadora Especializada de Plicometría', 'Motor de pliegues cutáneos', 6990, 'PENDIENTE_DE_VALIDACION',
  'NMX-36.xlsx', true),
('nmx15', 'NMX-15', 'Biblioteca Profesional de Fórmulas', 'Biblioteca de referencia transversal', 5990, 'v1.0',
  'NMX-15.xlsx', true),
('nmx21', 'NMX-21', 'Distribución Alimentaria (INTA 2018)', 'Base alimentaria y distribución', 7990, 'PENDIENTE_DE_VALIDACION',
  'NMX-21.xlsx', true),
('nmx43', 'NMX-43', 'Biblioteca UDD y Banco Clínico-Formativo (Bases de la Nutrición I y II)', 'Biblioteca de nutrientes y banco de casos', 7990, 'v1.2.0',
  'NMX-43.xlsx', true),
('nmx13', 'NMX-13', 'Recordatorio de 24 Horas (con catálogo PAL, NMX-01)', 'Evaluación dietética', 5990, 'v2.0.3',
  'NMX-13.xlsx', true),
('nmx17', 'NMX-17', 'Recordatorio de 24 Horas Conectado a Equivalentes', 'Evaluación dietética con equivalentes', 5990, 'PENDIENTE_DE_VALIDACION',
  'NMX-17.xlsx', true),
('nmx22', 'NMX-22', 'Registro Nutricional para Enfermedad Renal', 'Registro dietético renal', 6990, 'PENDIENTE_DE_VALIDACION',
  'NMX-22.xlsx', true),
('nmx24', 'NMX-24', 'Seguimiento Mensual de Hábitos (Habit Tracker)', 'Registro conductual', 4990, 'PENDIENTE_DE_VALIDACION',
  'NMX-24.xlsx', true),
('nmx29', 'NMX-29', 'Recordatorio de 24 Horas Renal', 'Evaluación dietética renal', 6990, 'PENDIENTE_DE_VALIDACION',
  'NMX-29.xlsx', true),
('nmx35', 'NMX-35', 'Diario Dietético y Conductual', 'Registro dietético-conductual', 4990, 'PENDIENTE_DE_VALIDACION',
  'NMX-35.xlsx', true),
('nmx41', 'NMX-41', 'Software Acompañante para Plicómetro', 'Control de calidad de medición antropométrica', 5990, 'v1.0',
  'NMX-41.xlsx', true),
('nmx02', 'NMX-02', 'Tabla Dietosintética Semanal', 'Planificación dietética', 5990, 'PENDIENTE_DE_VALIDACION',
  'NMX-02.xlsx', true),
('nmx07', 'NMX-07', 'Gestor de Creación de Dietas', 'Constructor de dietas', 7990, 'v2.0.1',
  'NMX-07.xlsx', true),
('nmx11', 'NMX-11', 'Planificador Integrado de Entrenamiento y Nutrición', 'Planificación deportiva', 6990, 'PENDIENTE_DE_VALIDACION',
  'NMX-11.xlsx', true),
('nmx25', 'NMX-25', 'Constructor de Platillos (Equivalentes Autorizados)', 'Constructor de recetas', 5990, 'PENDIENTE_DE_VALIDACION',
  'NMX-25.xlsx', true),
('nmx33', 'NMX-33', 'Planificador de Entrenamiento Semanal', 'Planificación de carga de entrenamiento', 5990, 'PENDIENTE_DE_VALIDACION',
  'NMX-33.xlsx', true),
('nmx03', 'NMX-03', 'Historia Clínica Nutricional Completa (Integración UDD)', 'Historia clínica nutricional', 7990, 'PENDIENTE_DE_VALIDACION',
  'NMX-03.xlsx', true),
('nmx06', 'NMX-06', 'Registro y Seguimiento de Composición Corporal', 'Seguimiento de composición corporal', 5990, 'v1.0.1',
  'NMX-06.xlsx', true),
('nmx08', 'NMX-08', 'Historia Clínica de Nutrición Deportiva', 'Historia clínica deportiva', 6990, 'v1.0',
  'NMX-08.xlsx', true),
('nmx20', 'NMX-20', 'Formulario Integral de Evaluación (Adulto, Persona Mayor, Hospital, Deporte, TEM, Frisancho)', 'Evaluación antropométrica integral', 7990, 'v3.0.1',
  'NMX-20.xlsx', true),
('nmx42', 'NMX-42', 'Explorador Renal de Alimentos y Equivalentes', 'Explorador dietético renal', 6990, 'PENDIENTE_DE_VALIDACION',
  'NMX-42.xlsx', true),
('nmx14i', 'NMX-14-INTEGRADO', 'Evaluación Nutricional Pediátrica Integral', 'Evaluación antropométrica pediátrica', 7990, 'v2.0.1',
  'NMX-14-INTEGRADO.xlsx', true),
('nmx14m', 'NMX-14-MINSAL-UDD', 'Evaluación Pediátrica OMS/MINSAL + UDD (Fuentes Resueltas)', 'Arquitectura documental pediátrica', 7990, 'v3.1.18',
  'NMX-14-MINSAL-UDD.xlsx', true),
('nmx28p', 'NMX-28-PACK', 'Guía del Pack de Antropometría (HUB)', 'Guía/mapa de paquete (documentación)', 4990, 'v1.0',
  'NMX-28-PACK.xlsx', true),
('nmx28i', 'NMX-28-INTEGRADO', 'Pack Antropometría Integrado (un solo archivo)', 'Suite antropométrica integrada', 7990, 'v2.1',
  'NMX-28-INTEGRADO.xlsx', true),
('nmx34', 'NMX-34', 'Indicador Educativo de Edad Metabólica', 'Indicador educativo / comunicación', 4990, 'PENDIENTE_DE_VALIDACION',
  'NMX-34.xlsx', true),
('nmxp1', 'NMX-P1', 'Guía del Paquete (Siete Herramientas)', 'Guía/mapa de paquete (documentación)', 4990, 'v1.0',
  'NMX-P1.xlsx', true)
ON CONFLICT (id) DO UPDATE SET
  sku = EXCLUDED.sku,
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  price_clp = EXCLUDED.price_clp,
  version = EXCLUDED.version,
  file_name = EXCLUDED.file_name,
  active = EXCLUDED.active;
